command:
  - ${env}
  - python3
  - examples/transformers/train_student.py
  -  ${args}
  - --wandb
  - --teacher-path
  - bert_teacher/checkpoints/best.pth
method: bayes
name: "bert-distilling"
project: "bert-distillation"
metric:
  name: accuracy
  goal: maximize
parameters:
  lr:
    values: [1e-5, 3e-5, 1e-4]
  batch-size:
    values: [8, 16, 32]
  alpha:
    values: [0.1, 0.3]
  beta:
    values: [0, 0.1, 0.2]
  kl-temperature:
    values: [2, 4]
  layers:
    values: ["1,3,5,7", "4,5,6,7"]
